[package]
name = "unet"
version = "0.0.0"
edition = "2024"

[dependencies]
arrayref = "0.3.9"
bytes = "1.10.1"
ethertype = "0.2.2"
libc = "0.2.172"
zerocopy = { version = "0.8.25", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
